apiVersion: v1
#resource type
kind: PersistentVolume
metadata:
  name: app-pv
  labels:
    vol: mysql
spec:
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: /data/app