apiVersion: apps/v1
kind: Deployment
metadata:
  name: mysql-deployment
spec:
  replicas: 1
  #The spec.selector field is required and must match the labels in spec.template.metadata.labels.
  selector:
    matchLabels:
      app: mysql
  template:
    metadata:
      labels:
        app: mysql
    spec:
      containers:
      - name: mysql
        #la imagen es la oficial de mysql de dockerhub
        image: mysql:8.0
        ports:
        - containerPort: 3306
        #dentro del contenedor se expondra en dir de los datos de la bbdd
        volumeMounts:
        - mountPath: /var/lib/mysql
          name: mysql-pd
        #declarar variables de entorno
        env:
        - name: MYSQL_ROOT_PASSWORD
          valueFrom:
            secretKeyRef:
              name: app-secret
              key: dbrootpass
        - name: MYSQL_USER
          valueFrom:
            secretKeyRef:
              name: app-secret
              key: dbuser
        - name: MYSQL_PASSWORD
          valueFrom:
            secretKeyRef:
              name: app-secret
              key: dbpass
        - name: MYSQL_DATABASE
          valueFrom:
            secretKeyRef:
              name: app-secret
              key: dbname
      #nombre del volumen que se monta
      volumes:
        - name: mysql-pd
          persistentVolumeClaim:
            claimName: app-pvc
