apiVersion: v1
kind: Service
metadata:
  name: mysql-service
spec:
  #if we don't specify the type of service it will be CLusterIP (internal)
  ports:
    - port: 3306
      protocol: TCP
      targetPort: 3306
  selector:
    app: mysql